### PR TITLE
Use context classLoader to load driver, if present.

### LINKED ISSUE #105: Use thread context classlaoder to load driver
If the jdbc driver class is not found when trying to load it (https://github.com/swaldman/c3p0/blob/master/src/java/com/mchange/v2/c3p0/DriverManagerDataSource.java#L143), a second attempt should be made using the `Thread.currentThread. getContextClassLoader()`

This would allow to have c3po loaded by a classloader while having the jdbc driver loaded by a descendant classloader.

### PR DESCRIPTION
**Pull request by elrodro83**
Fixes #105

### CODE REVIEW

**Comment by swaldman** [comment]
Hi.

Thanks very much for the contribution. This looks fine -- it would break nothing that works and help in some cases, i doubt very much there are users relying on failures to load driver classes within c3p0's classloader.

I have to ask you very informally to approve a CLA. If you consent, please e-mail at swaldman@mchange.com that i have your permission I ask your permission to 1) include and redistribute this under the existing choice of licenses; and 2) relicense the contribution on alternative terms as I see fit.

I don't love asking for (2), but not having that permission was a hassle when the library migrated from LGPL alone to choice of LGPL or EPL. In general, any relicensing would probably be to some alternative open source license, but I also use these libraries in consulting work and it's not inconceivable (although it has never actually happened so far) that some client would ask for a nonexclusive license on custom terms.

**Comment by elrodro83** [comment]
Hi @swaldman ,

I sent you the requested email yesterday.
Sorry for the delay.

Is there a chance of getting a new version out with his fix?
Thanks

**Comment by swaldman** [comment]
yes! sorry for my delay! i hope to do at least a new minor version soon. it has been much too long.

**Comment by xavier-rasschaert-privitar** [comment]
This PR would be very helpful to me as well. Any updates on when this could get merged and released?

**Comment by mikub** [comment]
Hi @swaldman, this PR seems very helpful, it definitely may happen that the driver is in the thread's context class loader, but c3p0 crashes stating the driver cannot be found. 
It would be terrific if we could get this merged and released.
Thanks heaps!

**Comment by swaldman** [comment]
Thanks!!!

I am very sorry to all for the ridiculous flake.

See https://github.com/swaldman/c3p0/commit/331e715dd32f20183a4b4f32afac3415a4cebcf9

**Pull request merged**
